nginx:
  build: nginx
  ports:
   - "8222:80"
  links:
   - hlapp:starman
  environment:
   - "VIRTUAL_HOST=harplayout.com"
  restart: always

hlapp:
  build: hlapp
  expose:
   - "9000"
  restart: always
