FROM nginx

COPY app /usr/share/nginx/html
COPY conf/default.conf /etc/nginx/conf.d/

RUN apt-get update
RUN apt-get install -y libswitch-perl libtemplate-perl cpanminus make gcc

RUN cpanm --installdeps CGI::Application::FastCGI

RUN cpanm --installdeps CGI::Application::Plugin::AnyTemplate
RUN cpanm --installdeps CGI::Application::Plugin::AutoRunmode
RUN cpanm Class::MethodMaker
